export const SOCIAL_CONTEXT_OFFICIAL =
  "QmbCKYo6fWgEP7PiqoYH1jKiJHWFCnGUmwxDfUUEjXQvXB";

export const GROUP_EXPRESSION_OFFICIAL =
  "QmR1WN8Xo9iExE5E7o42CEmSx3yXo8Eak8hWka39VTChRN";

export const PROFILE_EXPRESSION_OFFICIAL =
  "QmUdRBhq2FPz89e8KTZPoHKrPE2AhDRPrPEeov3BU44gtb";

export const SHORTFORM_EXPRESSION_OFFICIAL =
  "QmYrRhzvFPeyM48R7mAgox8iszXY8dGiUySZ4ZpG76ZWTh";

export const NOTE_IPFS_EXPRESSION_OFFICIAL =
  "QmYVsrMpiFmV9S7bTWNAkUzSqjRJskQ8g4TWKKwKrHAPqL";
