export const SOCIAL_CONTEXT_OFFICIAL =
  "QmbHEUC68JCwqKuLDSvjsWjcVjWFxoyBf5ffK7HLVYQyW4";

export const GROUP_EXPRESSION_OFFICIAL =
  "Qma6Jb7U5pYGkKw1KjitECUuzYQXiHU1kAwnYSVcNk7kGx";

export const NOTE_IPFS_EXPRESSION_OFFICIAL =
  "QmYVsrMpiFmV9S7bTWNAkUzSqjRJskQ8g4TWKKwKrHAPqL";
