export const SOCIAL_CONTEXT_OFFICIAL =
  "QmeG3xVQEqdXwjR4ceYuVEaL7x51RdUUY8A4hbNpbaVmxY";

export const GROUP_EXPRESSION_OFFICIAL =
  "QmceQMZTbHMkGFELB4EHGxXp7AknGTR6oddE6bNDLyBbCJ";

export const PROFILE_EXPRESSION_OFFICIAL =
  "QmPqoSEGi6zh7JTGj6bNA9xe6gkZDB176WssyXTXY7WyLB";

export const SHORTFORM_EXPRESSION_OFFICIAL =
  "QmThcYCiyNXUnZTD29gSLkHz3rdXeNNAxHUPCQAmLgB4Ad";

export const NOTE_IPFS_EXPRESSION_OFFICIAL =
  "Qmd6AZzLjfGWNAqWLGTGy354JC1bK26XNf7rTEEsJfv7Fe";
