export const SOCIAL_CONTEXT_OFFICIAL =
  "QmNnuZ5CgemAY2sskTqBbbHLvGJTqWByv4XaGLF2nrshzk";

export const GROUP_EXPRESSION_OFFICIAL =
  "QmUYFtkUdvjZE7JimrHjZv6qiexBpdLWxcRM9JJrfj3hgm";

export const PROFILE_EXPRESSION_OFFICIAL =
  "Qmc53vnQUXEMAyXP5DTaXYBLbp1mfP5xqJp5tUoELfCwk1";

export const SHORTFORM_EXPRESSION_OFFICIAL =
  "QmXU3mpKqDrcKnsP2BUzP6mUkn9zMGJQdHWi5VMLu2irSf";
