export default {
  id: "_c1lvoll6g",
  version: "2.0.0",
  name: "Untitled",
  description: "This is an example sprite",
  palette: [
    "fff0",
    "F2994A",
    "000",
    "9f7a5d",
    "5d432a",
    "b774d0",
    "3c4f89",
    "de597b",
    "75e8fa",
    "aea39f",
    "219653",
    "72a059",
    "7a9945",
    "5e5896",
    "a970d9",
    "903c7d",
    "8b4a39",
    "506b7f",
    "2d4b35",
    "4ca074",
    "763734",
    "919fb6",
    "5ba844",
    "8e4e51",
    "74e696",
    "EB5757",
    "2D9CDB",
  ],
  size: 11,
  fps: 10,
  frames: [
    "aaaacccaaaaaaacbbbcaaaaaacbbbcaaaaaaabbbaaaaaahhhhhhhaaahahhhhhahaabahhhhhabaaaakkkkkaaaaaaakakaaaaaaaakakaaaaaaaacacaaaa",
    "aaaadddaaaaaaddbbbddaaaaadbbbdaaaaaaabbbaaaaaaaagggaaaaaagggggggaaagagggggagaabagggggabaaaadddddaaaaaadaaadaaaaaacaaacaaa",
    "aaaadddaaaaaaadbbbdaaaaaadbbbdaaaaaadbbbdaaaaaadaiadaaaaaidiiidiaaaiaiiiiiaiaadaiiiiiadaaaaoooooaaaaaaoooooaaaaaaacacaaaa",
    "aaaasssaaaaaaaabbbaaaaaaabbbbbaaaaaaabbbaaaaaaaafffaaaaaafffffffaaafffffffffaabaafffaabaabaannnaabaaaaananaaaaaaaccaccaaa",
    "aaacccccaaaaaacbbbcaaaaaacbbbcaaaaaaabbbaaaaaaammmmmaaaaaammmmmaaaaaamqqqmaaaaaabqaqbaaaaaaaqaqaaaaaaaaqaqaaaaaaaacacaaaa",
    "aaaaeeeaaaaaaaebbbeaaaaaaebbbeaaaaaaebbbeaaaaalelllelaaalalllllalaabaalllaabaabaarrraabaaaaararaaaaaaaababaaaaaaaacacaaaa",
    "aaaeeeeeaaaaaeebbbeeaaaaeebbbeeaaaaaabbbaaaaaaapppppaaaaapannnapaaaapananapaaaaaababaaaaaaaababaaaaaaaababaaaaaaaccaccaaa",
    "aaaaaaaaaaaaaaabbbaaaaaaaabbbaaaaaaaabbbaaaaaajjjjjjjaaabajjjjjabaabajjjjjabaaaabbbbbaaaaaakkkkkaaaaaakaaakaaaaaacaaacaaa",
  ],
};
