export default {
  id: "_dxzkpihmy",
  version: "2.0.0",
  name: "Untitled",
  description: "This is an example sprite",
  palette: [
    "fff0",
    "219653",
    "89b37a",
    "9fa2ae",
    "83734f",
    "a7804b",
    "7e644c",
    "6FCF97",
    "ddb95a",
    "c8a25b",
    "a29566",
    "5f5449",
    "504c35",
    "d5d08c",
    "546685",
    "d7d75d",
    "917f5c",
  ],
  size: 11,
  fps: 10,
  frames: [
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahbbaaaaaaabbhbbaaaaahbhbbhbaaahbbbbbbbbaabhbbhbbhbahbbbbbbbbbb",
    "aaaccccccaaacccaecaaccacaaacccaacaaacccecccaaacaaeeaacaacaaaefaaaaaaacceecaaaaaaaefeaaaaaaaaaeeaaaaaaaaeefaaaaaaaaaeeaaaa",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadddddaaaaaafgfgiaaaaagfgfgfiaaaadddddddaaaagfgfgfiaaaadddddddaaaagfgfgfiaaaaadddddaaa",
  ],
};
