export default {
  id: "_dxzkpihmy",
  version: "2.0.0",
  name: "Untitled",
  description: "This is an example sprite",
  palette: [
    "fff0",
    "9fa2ae",
    "219653",
    "ce8e53",
    "89b37a",
    "a7804b",
    "83734f",
    "e0c362",
    "7e644c",
    "6FCF97",
    "ddb95a",
    "000",
    "fff",
    "F2994A",
    "EB5757",
    "b4b295",
    "e3b969",
    "c8a25b",
    "a29566",
    "5f5449",
    "504c35",
    "d5d08c",
    "546685",
    "d7d75d",
    "917f5c",
  ],
  size: 11,
  fps: 10,
  frames: [
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaajccaaaaaaaccjccaaaaajcjccjcaaajccccccccaacjccjccjcajcccccccccc",
    "aaaeeeeeeaaaeeeageaaeeaeaaaeeeaaeaaaeeegeeeaaaeaaggaaeaaeaaagfaaaaaaaaaggeaaaaaaaafgaaaaaaaaaggaaaaaaaaagfaaaaaaaaaggaaaa",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbaaaaaafifikaaaaaifififkaaaabbbbbbbaaaaifififkaaaabbbbbbbaaaaifififkaaaaabbbbbaaa",
    "aaaadddddaaaaaadaaadaaaaaadddddaaaaaadaaadaaaaahhhhhhaaaahhhhhhdaaaadadadadaaaadadadadaaaadadadadaaaadaaadaaaaaaaaaaaaaaa",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaabaabbaaaaaabaabbbbbbaabaambbbbbbablbbbbbbbbbaaaabbbbbbaaaabbaabbaaa",
  ],
};
